import json, sys, os, torch, numpy as np
sys.path.insert(0, os.path.dirname(__file__))
from ncps.wirings import AutoNCP
from ncps.torch import CfC
IN, OUT, UNITS = 15, 4, 108
wiring = AutoNCP(UNITS, OUT, sparsity_level=0.5, seed=22222)
model = CfC(IN, wiring, batch_first=True, return_sequences=True)
model.load_state_dict(torch.load(sys.argv[2] if len(sys.argv) > 2 else "/tmp/omg_brain.pt")["model"])
cell = model.rnn_cell
def r(t): return [round(float(v), 5) for v in t.detach().flatten().tolist()]
layers = []
nz = 0
for l in range(cell.num_layers):
    m = getattr(cell, f"layer_{l}")
    k = m.input_size + m.hidden_size
    w1 = (m.ff1.weight * m.sparsity_mask); w2 = (m.ff2.weight * m.sparsity_mask)
    nz += int((w1 != 0).sum()) + int((w2 != 0).sum())
    layers.append(dict(n=m.hidden_size, k=k, w1=r(w1), b1=r(m.ff1.bias), w2=r(w2), b2=r(m.ff2.bias),
                       wa=r(m.time_a.weight), ba=r(m.time_a.bias), wb=r(m.time_b.weight), bb=r(m.time_b.bias)))
brain = dict(inputs=IN, outputs=OUT, layers=layers)
out = sys.argv[1]
with open(out, "w") as f:
    f.write(".pragma library\n\n// Trained CfC/NCP weights (ncps AutoNCP wiring, %d units, %d inputs, %d outputs).\n// Generated by brain/export.py; do not edit by hand.\nvar BRAIN = " % (UNITS, IN, OUT))
    json.dump(brain, f, separators=(",", ":"))
    f.write("\n")
tot = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("exported", out, os.path.getsize(out) // 1024, "KB; trainable", tot, "; nonzero ff1/ff2 synapse weights", nz)
# parity fixture: a fixed random input sequence through the real ncps cell
torch.manual_seed(3)
X = torch.rand(1, 60, IN) * 2 - 1
D = torch.rand(1, 60) * 0.2 + 0.05
h = torch.zeros(1, cell.state_size); outs = []
with torch.no_grad():
    for t in range(60):
        o, h = cell(X[:, t], h, D[:, t:t + 1]); outs.append(o[0].tolist())
json.dump(dict(x=X[0].tolist(), dt=D[0].tolist(), y=outs), open(os.path.join(os.path.dirname(__file__), "parity.json"), "w"))
